#!/usr/bin/env node
var program = require('commander')
  , pkg = require('./package.json')
  , commands = require('./bin');

program
    .version(pkg.version)
    .usage('<command>')

Object.keys(commands).forEach(function(cmd) {
  commands[cmd](program);
});

program.parse(process.argv);
